POST https://localhost:5000/ketch/events
Content-Type: application/json
Accept: application/json
Authorization: Basic user1 password1

{
  "apiVersion":"dsr/v1",
  "kind":"AccessRequest",
  "metadata": {
    "uid":"D6EFAECD-2FCB-486D-B49A-4F699BFC24D1",
    "tenant":"axonic"
  },
  "request": {
    "property": "example.com",
    "environment": "production",
    "jurisdiction": "CCPA",
    "regulation": "CCPA",
    "subject": {
      "firstName": "JOE",
      "lastName": "SMITH",
      "phone": "1234567890",
      "email": "joe@example.com",
      "addressLine1": "123 MAIN ST",
      "addressLine2": "APT 34",
      "city": "ENGLEWOOD",
      "stateRegionCode": "MA",
      "postalCode": "10123-1234"
    },
    "identities": [
      {
        "identitySpace": "axonicID",
        "identityValue": "00015c60-37c5-11e9-83e4-0e7679b64802"
      }
    ],
    "callbacks": [
      {
        "url": "https://example.com/callback",
        "headers": {
          "Authorization": "Bearer $auth"
        }
      }
    ],
    "claims": {
    }
  }
}

> {%
client.test("Request returned successful status", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
client.test("Response returns JSON", function() {
  const type = response.contentType.mimeType;
  client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
});
client.test("Response returns Ketch format", function() {
  client.assert(response.body.hasOwnProperty("apiVersion"), "Cannot find 'apiVersion' option in response");
  client.assert(response.body.apiVersion === 'dsr/v1', "Wrong 'apiVersion'");
  client.assert(response.body.hasOwnProperty("kind"), "Cannot find 'kind' option in response");
  client.assert(response.body.kind === 'AccessResponse', "Wrong 'kind'");
  client.assert(response.body.hasOwnProperty("metadata"), "Cannot find 'metadata' option in response");
  client.assert(response.body.metadata.uid === 'd6efaecd-2fcb-486d-b49a-4f699bfc24d1', "Wrong 'uid'");
  client.assert(response.body.metadata.tenant === 'axonic', "Wrong 'tenant'");
  client.assert(response.body.hasOwnProperty("response"), "Cannot find 'response' option in response");
});
%}
