name: Pull Requests

on:
  pull_request:
    branches: [main]

jobs:
  build-go:
    name: Build go
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
          - registry: ghcr.io/ketch-com/ketch-event-forwarder
            localRegistry: localhost:5000/ketch-com/ketch-event-forwarder
            dockerfile: docker/ketch-event-forwarder/Dockerfile
      fail-fast: false
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    permissions:
      contents: read
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup .netrc
        uses: conventional-actions/setup-netrc@v1
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ env.GITHUB_TOKEN }}
      - name: Build docker image
        uses: docker/build-push-action@v5
        id: dockerbuild
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.images.dockerfile }}
          tags: ${{ matrix.images.localRegistry }}:latest
          # push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secret-files: |
            "netrc=/home/runner/.netrc"
      # - name: Run Snyk for linux/amd64
      #   uses: snyk/actions/docker@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}
      #   with:
      #     image: ${{ matrix.images.localRegistry }}:latest
      #     args: --file=${{ env.DOCKERFILE }} --severity-threshold=high --platform=linux/amd64
      # - name: Run Snyk for linux/arm64
      #   uses: snyk/actions/docker@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}
      #   with:
      #     image: ${{ matrix.images.localRegistry }}:latest
      #     args: --file=${{ env.DOCKERFILE }} --severity-threshold=high --platform=linux/arm64

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
